# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Visual Studio Professional (c5e3f6a1-9951-44ab-aa57-12d7bdb5b79a)'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       dir
#       Write-Host Build $Build.ArtifactStagingDirectory
#       Write-Host PipelineWorkspace $Pipeline.Workspace
#       Write-Host system $System.DefaultWorkingDirectory	
#       dir
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Visual Studio Professional (c5e3f6a1-9951-44ab-aa57-12d7bdb5b79a)'
    ScriptType: 'FilePath'
    ScriptPath: '$PipelineWorkspace.CubeItUp.Infrastructure.DeployInfrastructure.ps1'
    azurePowerShellVersion: 'LatestVersion'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
