trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: deploymentFile 
  value: deploy.yml
- name: InfrastructurePath
  # value: CubeItUpInfrastructure/s/CubeItUp.Infrastructure
  value: CubeItUp.Infrastructure

stages:
- stage: PublishArtifact
  jobs: 
  - job: PublishArtifact
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '${{ variables.InfrastructurePath }}'
        artifact: 'CubeItUpInfrastructure'
        publishLocation: 'pipeline'

- template: ${{ variables.deploymentFile }}
  parameters: 
    environment: 'dev'
