trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: deploymentFile 
  value: deploy.yml

- template: $(deploymentFile)
  parameters: 
    environmentPrefix: d

# - template: $deploymentFile
#   parameters: p