trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: deploymentFile 
  value: deploy.yml

- template: ${{ variables.deploymentFile }}
  parameters: 
    environmentPrefix: d

# - template: $deploymentFile
#   parameters: p