trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: deploymentFile 
  value: deploy.yml
- name: InfrastructurePath
  value: CubeItUpInfrastructure/s/CubeItUp.Infrastructure

stages:
- stage: Publish Artifact
  jobs: 
  - job: PublishArtifact
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/$ {{ variables.InfrastructurePath }}'
        artifact: 'CubeItUpInfrastructure'
        publishLocation: 'pipeline'

- template: ${{ variables.deploymentFile }}
  parameters: 
    environmentPrefix: 'd'