trigger:
- master

pool:
  vmImage: windows-latest

variables:
- name: deploymentFile 
  value: deploy.yml

- template: $deploymentFile
  parameters: d

# - template: $deploymentFile
#   parameters: p