trigger:
- master

pool:
  vmImage: windows-latest

- variables:
  deploymentFile: deploy.yml

- template: Deploy infrastructure dev
  parameters: d

- template: Deploy infrastructure prod
  parameters: p