parameters:
- name: environmentPrefix
  type: string
  default: 'd'
  # values:
  #   - 'd'
  #   - p

stages:
- stage: DeployInfrastructure
  displayName: Deploy Infrastructure
  jobs:
  - deployment:
    displayName: 'Deploy infrastructure powershell script'
    environment: 'CubeItUp'    
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Visual Studio Professional (c5e3f6a1-9951-44ab-aa57-12d7bdb5b79a)'
              ScriptType: 'InlineScript'
              Inline: |
                dir
                Write-Host 'hei'
                dir
              azurePowerShellVersion: 'LatestVersion'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Visual Studio Professional (c5e3f6a1-9951-44ab-aa57-12d7bdb5b79a)'
              scriptType: 'ps'
              scriptLocation: 'scriptPath'
              scriptPath: 'CubeItUp.Infrastructure/DeployInfrastructure.ps1'