parameters:
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'prod'

stages:
- stage: DeployInfrastructure
  displayName: Deploy Infrastructure ${{ parameters.environment }}
  jobs:
  - deployment:
    displayName: 'Deploy infrastructure powershell script'
    environment: 'CubeItUp'    
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Visual Studio Professional (c5e3f6a1-9951-44ab-aa57-12d7bdb5b79a)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/CubeItUpInfrastructure/DeployInfrastructure.ps1'
              ScriptArguments: '-environment ${{ parameters.environment }}'
              azurePowerShellVersion: 'LatestVersion'
